[package]
name = "veac-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
schemars = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_json_canonicalizer = "0.3"
veac-artifact = { path = "../veac-artifact" }
veac-ir = { path = "../veac-ir" }
