"""Shared Rust naming and output paths for executable stdlib generation."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPE_ROOT = ROOT / "crates/veac-lang-model/src/domain_type/generated"
OP_ROOT = ROOT / "crates/veac-domain-spec/src/operation_id/generated"
CONTRACT_ROOT = ROOT / "crates/veac-domain-spec/src/catalog/generated"
IR_OPCODE_ROOT = ROOT / "crates/veac-ir/src/validation/provenance/generated"
PRIMITIVE_RUST = {
    "int": "Integer", "scalar": "Scalar", "time": "Time", "length": "Length",
    "percent": "Percent", "angle": "Angle", "text": "Text", "color": "Color",
    "bool": "Boolean", "identifier": "Identifier",
}
HEADER = "// @generated by scripts/stdlib_codegen.py; do not edit.\n"


def pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]", value))


def snake_type(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def op_constant(operation) -> str:
    prefix = operation["receiver"] or ""
    return prefix + pascal(operation["name"])


def family_groups(operations):
    values = defaultdict(list)
    for operation in operations:
        values[operation["family"]].append(operation)
    return values


def opcode_ranges(opcodes):
    output = []
    start = previous = opcodes[0]
    for value in opcodes[1:] + [None]:
        if value is not None and value == previous + 1:
            previous = value
            continue
        output.append(
            f"0x{start:04x}" if start == previous else f"0x{start:04x}..=0x{previous:04x}"
        )
        start = previous = value
    return output
