"""Shared Rust naming and output paths for executable stdlib generation."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPE_ROOT = ROOT / "crates/veac-lang/src/program/domain_system/domain_type/generated"
OP_ROOT = ROOT / "crates/veac-lang/src/program/domain_system/operation_id/generated"
CONTRACT_ROOT = ROOT / "crates/veac-lang/src/program/domain_system/catalog/generated"
IR_OPCODE_ROOT = ROOT / "crates/veac-ir/src/validation/provenance/generated"
PRIMITIVE_RUST = {
    "int": "Integer", "scalar": "Scalar", "time": "Time", "length": "Length",
    "percent": "Percent", "angle": "Angle", "text": "Text", "color": "Color",
    "bool": "Boolean", "identifier": "Identifier",
}
HEADER = "// @generated by scripts/stdlib_codegen.py; do not edit.\n"


def pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]", value))


def snake_type(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def op_constant(operation) -> str:
    prefix = operation["receiver"] or ""
    return prefix + pascal(operation["name"])


def family_groups(operations):
    values = defaultdict(list)
    for operation in operations:
        values[operation["family"]].append(operation)
    return values
